apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  hostname: {{ .Values.mapping.hostname | quote }}
  prefix: {{ .Values.mapping.prefix | quote }}
  service: {{ include "meet-assist.fullname" . }}:{{ .Values.service.port }}