apiVersion: v1
kind: Service
metadata:
  name: {{ include "meet-assist.fullname" . }}
  labels:
    {{- include "meet-assist.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "meet-assist.selectorLabels" . | nindent 4 }}